### ISSUE TITLE
fix .pyup.yml

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#9391]
In the process of writing #9390 I thought I'd fix `.pyup.yml` too, but I doubt it was working anyway.  We have:
```
requirements:
  - requirements/dev.txt:
      updates: all
  - requirements/prod.txt:
      updates: security
  - requirements/docs.txt:
      updates: all
```
But according to https://pyup.io/docs/bot/config/ it's `update` not `updates`; and `insecure` not `security`.  It likely only works because the defaults it to search in common locations (such as `/requirements/`) and `update` defaults to `all`.
